// opponents.js — All opponent definitions

export const OPPONENTS = [
    // === MINOR CIRCUIT ===
    {
        name: "Glass Joe",
        nationality: "France",
        record: "1-99",
        circuit: "Minor",
        hp: 100,
        defense: 2,
        attackSpeed: 0.7,
        idleMinFrames: 90,
        idleMaxFrames: 180,
        knockdownGetUpChance: 0.2,
        maxKnockdowns: 1,
        counterWindowBonus: 1.5,
        spriteColor: "#4488ff",
        skinColor: "#f0c8a0",
        hairColor: "#aa7744",
        shortsColor: "#4488ff",
        glovesColor: "#cc2222",
        headgearColor: "#4488ff",
        bodyWidth: 36,
        bodyHeight: 55,
        portrait: 'glassJoe',
        patterns: [
            {
                type: 'jab',
                hand: 'right',
                telegraph: 45,
                recovery: 35,
                damage: 6,
                dodgeDirection: 'left',
                speed: 3,
                tellAnim: 'pullBackRight'
            },
            {
                type: 'jab',
                hand: 'left',
                telegraph: 45,
                recovery: 35,
                damage: 6,
                dodgeDirection: 'right',
                speed: 3,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 55,
                recovery: 40,
                damage: 12,
                dodgeDirection: 'left',
                speed: 2,
                tellAnim: 'windUpRight'
            }
        ],
        advice: "He's the weakest boxer. Just punch him!"
    },
    {
        name: "Von Kaiser",
        nationality: "Germany",
        record: "23-13",
        circuit: "Minor",
        hp: 120,
        defense: 3,
        attackSpeed: 0.85,
        idleMinFrames: 70,
        idleMaxFrames: 150,
        knockdownGetUpChance: 0.4,
        maxKnockdowns: 2,
        counterWindowBonus: 1.4,
        spriteColor: "#665533",
        skinColor: "#f0c8a0",
        hairColor: "#665533",
        shortsColor: "#333333",
        glovesColor: "#882222",
        headgearColor: null,
        bodyWidth: 38,
        bodyHeight: 56,
        portrait: 'vonKaiser',
        patterns: [
            {
                type: 'jab',
                hand: 'left',
                telegraph: 38,
                recovery: 30,
                damage: 8,
                dodgeDirection: 'right',
                speed: 4,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'jab',
                hand: 'right',
                telegraph: 38,
                recovery: 30,
                damage: 8,
                dodgeDirection: 'left',
                speed: 4,
                tellAnim: 'pullBackRight'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 40,
                recovery: 35,
                damage: 14,
                dodgeDirection: 'left',
                speed: 4,
                tellAnim: 'shakeHead'
            },
            {
                type: 'hook',
                hand: 'left',
                telegraph: 40,
                recovery: 35,
                damage: 14,
                dodgeDirection: 'right',
                speed: 4,
                tellAnim: 'shakeHead'
            }
        ],
        advice: "Watch for the head shake before his hooks!"
    },
    {
        name: "Piston Honda",
        nationality: "Japan",
        record: "26-1",
        circuit: "Minor",
        hp: 150,
        defense: 5,
        attackSpeed: 1.0,
        idleMinFrames: 50,
        idleMaxFrames: 120,
        knockdownGetUpChance: 0.55,
        maxKnockdowns: 2,
        counterWindowBonus: 1.3,
        spriteColor: "#ffffff",
        skinColor: "#f0d0a0",
        hairColor: "#222222",
        shortsColor: "#ffffff",
        glovesColor: "#cc2222",
        headgearColor: null,
        headband: "#ff0000",
        bodyWidth: 38,
        bodyHeight: 58,
        portrait: 'pistonHonda',
        patterns: [
            {
                type: 'jab',
                hand: 'left',
                telegraph: 30,
                recovery: 25,
                damage: 10,
                dodgeDirection: 'right',
                speed: 5,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'jab',
                hand: 'right',
                telegraph: 30,
                recovery: 25,
                damage: 10,
                dodgeDirection: 'left',
                speed: 5,
                tellAnim: 'pullBackRight'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 35,
                recovery: 30,
                damage: 16,
                dodgeDirection: 'left',
                speed: 5,
                tellAnim: 'windUpRight'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 50,
                recovery: 45,
                damage: 22,
                dodgeDirection: 'duck',
                speed: 6,
                tellAnim: 'stepBack',
                specialName: 'Honda Rush'
            }
        ],
        advice: "He steps back before the Honda Rush. Duck it!"
    },
    // === MAJOR CIRCUIT ===
    {
        name: "Don Flamenco",
        nationality: "Spain",
        record: "22-3",
        circuit: "Major",
        hp: 130,
        defense: 4,
        attackSpeed: 0.95,
        idleMinFrames: 60,
        idleMaxFrames: 130,
        knockdownGetUpChance: 0.5,
        maxKnockdowns: 2,
        counterWindowBonus: 1.6,
        spriteColor: "#ff4444",
        skinColor: "#e8c090",
        hairColor: "#222222",
        shortsColor: "#ff4444",
        glovesColor: "#ffcc00",
        headgearColor: null,
        bodyWidth: 38,
        bodyHeight: 56,
        portrait: 'donFlamenco',
        patterns: [
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 42,
                recovery: 38,
                damage: 18,
                dodgeDirection: 'left',
                speed: 5,
                tellAnim: 'flamencoSpin'
            },
            {
                type: 'jab',
                hand: 'left',
                telegraph: 32,
                recovery: 28,
                damage: 10,
                dodgeDirection: 'right',
                speed: 5,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 38,
                recovery: 32,
                damage: 15,
                dodgeDirection: 'left',
                speed: 5,
                tellAnim: 'windUpRight'
            }
        ],
        advice: "Dodge his uppercut and counter quickly!"
    },
    {
        name: "King Hippo",
        nationality: "Hippo Island",
        record: "18-9",
        circuit: "Major",
        hp: 170,
        defense: 7,
        attackSpeed: 0.75,
        idleMinFrames: 80,
        idleMaxFrames: 160,
        knockdownGetUpChance: 0.0,
        maxKnockdowns: 1,
        counterWindowBonus: 2.0,
        spriteColor: "#6688aa",
        skinColor: "#88aacc",
        hairColor: "#445566",
        shortsColor: "#6688aa",
        glovesColor: "#cc2222",
        headgearColor: null,
        crown: "#ffcc00",
        bodyWidth: 50,
        bodyHeight: 60,
        portrait: 'kingHippo',
        isKingHippo: true,
        patterns: [
            {
                type: 'hook',
                hand: 'right',
                telegraph: 50,
                recovery: 50,
                damage: 20,
                dodgeDirection: 'left',
                speed: 3,
                tellAnim: 'openMouth'
            },
            {
                type: 'hook',
                hand: 'left',
                telegraph: 50,
                recovery: 50,
                damage: 20,
                dodgeDirection: 'right',
                speed: 3,
                tellAnim: 'openMouth'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 60,
                recovery: 60,
                damage: 28,
                dodgeDirection: 'duck',
                speed: 3,
                tellAnim: 'openMouthWide',
                specialName: 'Belly Flop'
            }
        ],
        advice: "Hit his face when his mouth opens, then pummel the body!"
    },
    {
        name: "Great Tiger",
        nationality: "India",
        record: "24-5",
        circuit: "Major",
        hp: 155,
        defense: 5,
        attackSpeed: 1.1,
        idleMinFrames: 45,
        idleMaxFrames: 110,
        knockdownGetUpChance: 0.5,
        maxKnockdowns: 2,
        counterWindowBonus: 1.3,
        spriteColor: "#ff8800",
        skinColor: "#c09060",
        hairColor: "#222222",
        shortsColor: "#ff8800",
        glovesColor: "#ffcc00",
        headgearColor: null,
        turban: "#ff8800",
        bodyWidth: 38,
        bodyHeight: 56,
        portrait: 'greatTiger',
        patterns: [
            {
                type: 'jab',
                hand: 'right',
                telegraph: 28,
                recovery: 25,
                damage: 12,
                dodgeDirection: 'left',
                speed: 6,
                tellAnim: 'pullBackRight'
            },
            {
                type: 'uppercut',
                hand: 'left',
                telegraph: 35,
                recovery: 30,
                damage: 16,
                dodgeDirection: 'right',
                speed: 6,
                tellAnim: 'gemFlash'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 40,
                recovery: 40,
                damage: 20,
                dodgeDirection: 'duck',
                speed: 7,
                tellAnim: 'tigerSpin',
                specialName: 'Tiger Spin'
            }
        ],
        advice: "His gem flashes before the magic uppercut. The spin is tricky - duck it!"
    },
    // === WORLD CIRCUIT ===
    {
        name: "Bald Bull",
        nationality: "Turkey",
        record: "34-4",
        circuit: "World",
        hp: 185,
        defense: 6,
        attackSpeed: 1.15,
        idleMinFrames: 40,
        idleMaxFrames: 100,
        knockdownGetUpChance: 0.6,
        maxKnockdowns: 2,
        counterWindowBonus: 1.2,
        spriteColor: "#884422",
        skinColor: "#8B6914",
        hairColor: "#000000",
        shortsColor: "#884422",
        glovesColor: "#cc2222",
        headgearColor: null,
        bodyWidth: 42,
        bodyHeight: 60,
        portrait: 'baldBull',
        patterns: [
            {
                type: 'jab',
                hand: 'left',
                telegraph: 25,
                recovery: 22,
                damage: 14,
                dodgeDirection: 'right',
                speed: 7,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 30,
                recovery: 28,
                damage: 18,
                dodgeDirection: 'left',
                speed: 7,
                tellAnim: 'windUpRight'
            },
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 32,
                recovery: 30,
                damage: 22,
                dodgeDirection: 'duck',
                speed: 7,
                tellAnim: 'crouchDown'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 55,
                recovery: 55,
                damage: 35,
                dodgeDirection: 'counter',
                speed: 8,
                tellAnim: 'bullCharge',
                specialName: 'Bull Charge',
                mustCounter: true
            }
        ],
        advice: "Counter-punch during the Bull Charge or you can't stop him!"
    },
    {
        name: "Soda Popinski",
        nationality: "Russia",
        record: "33-2",
        circuit: "World",
        hp: 195,
        defense: 6,
        attackSpeed: 1.2,
        idleMinFrames: 35,
        idleMaxFrames: 90,
        knockdownGetUpChance: 0.6,
        maxKnockdowns: 2,
        counterWindowBonus: 1.2,
        spriteColor: "#dd3333",
        skinColor: "#e8a0a0",
        hairColor: "#cc3333",
        shortsColor: "#dd3333",
        glovesColor: "#cc2222",
        headgearColor: null,
        bodyWidth: 42,
        bodyHeight: 60,
        portrait: 'sodaPopinski',
        patterns: [
            {
                type: 'jab',
                hand: 'left',
                telegraph: 22,
                recovery: 20,
                damage: 14,
                dodgeDirection: 'right',
                speed: 7,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 28,
                recovery: 25,
                damage: 20,
                dodgeDirection: 'left',
                speed: 7,
                tellAnim: 'windUpRight'
            },
            {
                type: 'uppercut',
                hand: 'left',
                telegraph: 30,
                recovery: 28,
                damage: 24,
                dodgeDirection: 'right',
                speed: 8,
                tellAnim: 'drinkSoda'
            },
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 30,
                recovery: 28,
                damage: 24,
                dodgeDirection: 'left',
                speed: 8,
                tellAnim: 'crouchDown'
            }
        ],
        advice: "He drinks soda to power up. Hit him when he drinks!"
    },
    {
        name: "Mr. Sandman",
        nationality: "USA",
        record: "31-2",
        circuit: "World",
        hp: 210,
        defense: 7,
        attackSpeed: 1.3,
        idleMinFrames: 30,
        idleMaxFrames: 80,
        knockdownGetUpChance: 0.65,
        maxKnockdowns: 2,
        counterWindowBonus: 1.1,
        spriteColor: "#334455",
        skinColor: "#6B4226",
        hairColor: "#111111",
        shortsColor: "#334455",
        glovesColor: "#cc2222",
        headgearColor: null,
        bodyWidth: 44,
        bodyHeight: 62,
        portrait: 'mrSandman',
        patterns: [
            {
                type: 'jab',
                hand: 'right',
                telegraph: 20,
                recovery: 18,
                damage: 16,
                dodgeDirection: 'left',
                speed: 8,
                tellAnim: 'pullBackRight'
            },
            {
                type: 'hook',
                hand: 'left',
                telegraph: 25,
                recovery: 22,
                damage: 22,
                dodgeDirection: 'right',
                speed: 8,
                tellAnim: 'windUpLeft'
            },
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 28,
                recovery: 25,
                damage: 26,
                dodgeDirection: 'duck',
                speed: 8,
                tellAnim: 'crouchDown'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 35,
                recovery: 35,
                damage: 30,
                dodgeDirection: 'duck',
                speed: 9,
                tellAnim: 'dreamcatcher',
                specialName: 'Dreamland Express'
            }
        ],
        advice: "Three uppercuts in a row - dodge them all to find an opening!"
    },
    {
        name: "Super Macho Man",
        nationality: "Hollywood",
        record: "35-0",
        circuit: "World",
        hp: 220,
        defense: 7,
        attackSpeed: 1.35,
        idleMinFrames: 30,
        idleMaxFrames: 75,
        knockdownGetUpChance: 0.55,
        maxKnockdowns: 2,
        counterWindowBonus: 1.1,
        spriteColor: "#ffcc00",
        skinColor: "#e8c8a0",
        hairColor: "#ccaa44",
        shortsColor: "#ffcc00",
        glovesColor: "#cc2222",
        headgearColor: null,
        sunglasses: "#222222",
        bodyWidth: 44,
        bodyHeight: 60,
        portrait: 'superMachoMan',
        patterns: [
            {
                type: 'jab',
                hand: 'left',
                telegraph: 18,
                recovery: 18,
                damage: 16,
                dodgeDirection: 'right',
                speed: 8,
                tellAnim: 'pullBackLeft'
            },
            {
                type: 'hook',
                hand: 'right',
                telegraph: 24,
                recovery: 22,
                damage: 22,
                dodgeDirection: 'left',
                speed: 8,
                tellAnim: 'flexRight'
            },
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 26,
                recovery: 24,
                damage: 24,
                dodgeDirection: 'duck',
                speed: 9,
                tellAnim: 'crouchDown'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 40,
                recovery: 35,
                damage: 32,
                dodgeDirection: 'duck',
                speed: 9,
                tellAnim: 'spinPunch',
                specialName: 'Super Spin Punch'
            }
        ],
        advice: "His spin punch is devastating but slow. Duck and counter!"
    },
    // === DREAM FIGHT ===
    {
        name: "Mike Tyson",
        nationality: "USA",
        record: "31-0",
        circuit: "Dream",
        hp: 255,
        defense: 8,
        attackSpeed: 1.5,
        idleMinFrames: 20,
        idleMaxFrames: 60,
        knockdownGetUpChance: 0.7,
        maxKnockdowns: 3,
        counterWindowBonus: 1.0,
        spriteColor: "#111111",
        skinColor: "#6B4226",
        hairColor: "#111111",
        shortsColor: "#111111",
        glovesColor: "#cc2222",
        headgearColor: null,
        bodyWidth: 44,
        bodyHeight: 62,
        portrait: 'mikeTyson',
        isTyson: true,
        patterns: [
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 15,
                recovery: 15,
                damage: 96,
                dodgeDirection: 'left',
                speed: 10,
                tellAnim: 'wink',
                isInstantKO: true,
                firstPhaseOnly: true
            },
            {
                type: 'uppercut',
                hand: 'left',
                telegraph: 15,
                recovery: 15,
                damage: 96,
                dodgeDirection: 'right',
                speed: 10,
                tellAnim: 'wink',
                isInstantKO: true,
                firstPhaseOnly: true
            },
            {
                type: 'jab',
                hand: 'right',
                telegraph: 15,
                recovery: 14,
                damage: 18,
                dodgeDirection: 'left',
                speed: 9,
                tellAnim: 'pullBackRight'
            },
            {
                type: 'hook',
                hand: 'left',
                telegraph: 18,
                recovery: 16,
                damage: 24,
                dodgeDirection: 'right',
                speed: 9,
                tellAnim: 'windUpLeft'
            },
            {
                type: 'uppercut',
                hand: 'right',
                telegraph: 20,
                recovery: 18,
                damage: 30,
                dodgeDirection: 'duck',
                speed: 9,
                tellAnim: 'crouchDown'
            },
            {
                type: 'special',
                hand: 'both',
                telegraph: 18,
                recovery: 20,
                damage: 40,
                dodgeDirection: 'duck',
                speed: 10,
                tellAnim: 'wink',
                specialName: 'Dynamite Uppercut'
            }
        ],
        advice: "The first 90 seconds are all instant-KO uppercuts. Survive!"
    }
];

export function getOpponent(index) {
    return { ...OPPONENTS[index] };
}

export function getCircuitOpponents(circuit) {
    return OPPONENTS.filter(o => o.circuit === circuit);
}
